// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpawhflhabnqwobahuqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwYXdoZmxoYWJucXdvYmFodXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTE1MzEsImV4cCI6MjA2ODgyNzUzMX0.-rsfVMAcAbi_nFBhnojH5IGuP2-7CF_mAJu_xLiACYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});